### ISSUE TITLE
Kako osigurati da prozor aplikacije ostane otvoren nakon izvođenja koda?

### ISSUE THREAD

**Issue by lovrosverko** [GabrielMatoBoopetyScoopWoop/KartaskaIgra#1]
https://github.com/GabrielMatoBoopetyScoopWoop/KartaskaIgra/blob/34913ac63594e8e3a34f66e8d116bc85c145adcf/KartaskaIgra/Program.cs#L32

Na kraju koda dodaš:
Console.ReadKey();

**Comment by GabrielMatoBoopetyScoopWoop** [comment]
Ja sam samo napisao kod i nisam puno mislio o testiranju, ubuduće ću dodati
tu liniju u svoje programe (osim ako ne trebam).

I ime mi je grozno, ne znam kako da promjenim. Će to biti problem? Da
napravim novi github?

**Comment by GabrielMatoBoopetyScoopWoop** [comment]
Riješio sam problem.
